apiVersion: v1
data:
  tls.crt: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUREakNDQWZhZ0F3SUJBZ0lVQmNMam
    xuakNONnMwZzM5dThFUFhoczNwV3ZRd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0dURVhNQlVH
    QTFVRUF3d09ZMkV1WlhoaGJYQnNaUzVqYjIwd0hoY05Nall3TXpNeE1ERTBPVEV4V2hjTg
    pNamN3TXpNeE1ERTBPVEV4V2pBbE1TTXdJUVlEVlFRRERCcDNaV0pvYjI5ckxYTmxjblpw
    WTJVdWMzbHpkR1Z0CkxuTjJZekNDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0
    NBUW9DZ2dFQkFNblZYWSt4c0pKSnZTd0MKYjY0OEQwMjNLUktrMXFYN2tUZnAwZGR6a0ZO
    ZkU0VUxHcWsyMzE5V3dWbnJOSlY5Ry9uSE9wNzZ3d3o1Y0FlZwp0ampBK0R2eVdZSndicm
    YxRDFTcVNiSkpmcFB1MzkxKzNJZUh3RU1pWE1zRktiRzBBMXFNU0IxRTQ0QkRDNWNsCmVl
    VnJjWnJhSmcvT1BwTUlzdlhER3RqcTNscTRxaHg5aWkxSHZ6QVZ5OTZCeDQ4ODRaMkwyWH
    JVbTlrQk4vYm0KdmRtTVBTM2lPL1p4cmpPRHJnaEdJeXNZNlc3ak5zUVVGZnZka2cwNHpz
    enN2TmdyYWJQOE9GR1lsSUdmWHFZbwpyZ1JuUkdVRmxNeGhUSTFNSGJpTnZoenFUenRIUW
    cvVHptWU9lMVNpTWlKbE0vQTRWVFFQUmtjUXVYdFZOLzhnCnAwaWg3c01DQXdFQUFhTkNN
    RUF3SFFZRFZSME9CQllFRkRocnhvY0NxY09ETFVyWEpnRjJwcTNreDNKQU1COEcKQTFVZE
    l3UVlNQmFBRkpQb0NoWkJHOE8zekliUlBSRTJ0c3E1MUFick1BMEdDU3FHU0liM0RRRUJD
    d1VBQTRJQgpBUUFreFg4WFQyeVptMURlWjgyeE1UQXU4MllCMEVmcTJxZUx0S2FlMk1OTj
    JaQlArYWZheWpFekNuMFhxV2VoCnc4ak0wMTJOOFM4eWZRQkFWWlc3bmJ2bWVFY0ZQS1Zm
    NUtKUWRxb0paTjhiY1N0bHFWbHlPVzR2bnc4NG1PY3MKdjVMMnpSMUJVb2RxSXltN01uRV
    NuWXBnYWxmVndlelQxWFVlaEhDV0FoUVQ3ZW1JOGhudnREUmlqMVhReGpuSwphQ3YxUWIw
    U3k3QmxWb3VQaGtuT1IzYnl2Ylo3NnZUckpWeXAraStNNWhyYnI4NmVOMGF5QzhaZGQwel
    pjNmpyCmUyU3AyMHE4TmFKamx4TGVaQUoxeFczTFlXVC9sbFdCVkNmdHplZVNQdnlOeEFV
    VzhCVlFFS3VMQVp4QkF3YUMKZHhHaG9TdnVNRlhHcXQyRGU0Rjl5RnVhCi0tLS0tRU5EIE
    NFUlRJRklDQVRFLS0tLS0K
  tls.key: |
    LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQk
    FRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRREoxVjJQc2JDU1NiMHMKQW0rdVBBOU50eWtT
    cE5hbCs1RTM2ZEhYYzVCVFh4T0ZDeHFwTnQ5ZlZzRlo2elNWZlJ2NXh6cWUrc01NK1hBSA
    pvTFk0d1BnNzhsbUNjRzYzOVE5VXFrbXlTWDZUN3QvZGZ0eUhoOEJESWx6TEJTbXh0QU5h
    akVnZFJPT0FRd3VYCkpYbmxhM0dhMmlZUHpqNlRDTEwxd3hyWTZ0NWF1S29jZllvdFI3OH
    dGY3ZlZ2NlUFBPR2RpOWw2MUp2WkFUZjIKNXIzWmpEMHQ0anYyY2E0emc2NElSaU1yR09s
    dTR6YkVGQlg3M1pJTk9NN003THpZSzJtei9EaFJtSlNCbjE2bQpLSzRFWjBSbEJaVE1ZVX
    lOVEIyNGpiNGM2azg3UjBJUDA4NW1EbnRVb2pJaVpUUHdPRlUwRDBaSEVMbDdWVGYvCklL
    ZElvZTdEQWdNQkFBRUNnZ0VBUy92TUI5dEUxcVgxRmxycWNZVkIyNmVmU2xvTlJ4cWdycF
    NUdjlGTlhkMjIKeXdrRnBmdTI5ejBCZUprZ1NFRDc1YnAzMnI4YjdFZ0J3WlZpMUpYdFBp
    QThTMnVKZXk3Q2NVVFVqczYxWFByNgpnM2dOak9aeDNyUlNpOG5yU3UreXJZV1BacGwzTG
    1QUE9yMU1tUzZzYTdoQnlRU0RzVFgrcmFBZ2ZOWmJGSHF5Cm5HdnF2bnBCeW5rOHZtNi9H
    cWtTcHp4SHZYcFJGWWREVlFNc1E2ZmpnTGhIKytIMDBqeTBwbHkwVXZaUlBHVkMKcHNleX
    JaektnTEhlV3lxcVh0amtGbThtR1llVnhkdExBMTRmUGNiTHhoRHVSODROVmlmWFQ5ckhZ
    cmVvOHhsTgowUm5pVEtMSkpJVGJBUHRtdTNnNjNEWFU0bEk0aVNmV04wLys1Z1lKTlFLQm
    dRRHRXM2pheTVGMmJrczNFeHJyCmpJNFUxRUNkaUtXcm01SHBIVjhmVUJIbkhSeWxaeHU4
    eldrNFNhV1R2MmZWcVV4MEM2UnRPMVgvMmgrVFloL3cKWk5qZnphRFNaKzBBQml6eDYvMn
    ZGZENQbXJyVUlqTXhTTVAvM05CT0ZJYnkrTDQ2YlUwNVR6R3Fwemd0QTJYcAoxU3ZudFc5
    akZjQWpRbHBEODdVMnlpY2Y3d0tCZ1FEWnI1NGFEc0wvUXczbk5YQkx3cGxwY3Y0cGZBMk
    lVazY3Cjl4eUpjSG02UVJycGxNZE1Qa1VZaFgwTlNMcURGOGw2Ujgvd0ZWVVRVVmlCQTJu
    L3Fua1NBZ0drREJIWGpEQVcKYkg0TWZUczRuaVZBR3NnSUtka2gxemNUeVNBcUJ3R0d2Rm
    xzRlZ6RFVnYzRYK2oxVUtBQm1lZnoxWU5CQWFMcwozNUJLNHVZS2JRS0JnQ0VQSkg0VTdH
    VzZadTk4MGJzTkVKMEdFeG5kOW5VNGJkSXlMUldIYVhidkx4WTZqanAxCndibjlSL3FVSm
    pvMElsbm5aVGR4bEVEV2VKOW1nMXhRTDRTOGR6SFhGOE54R01GNVJSUWx6YTZ5dG1MbGdJ
    dlUKdnJmY1lZYitoTzFDaC94TFRQNDJjWXg3VGUrM0VYTElKaDFYdi9QbEM2WGRrQVQyNU
    w2RTJYNHhBb0dBRFl4MwpxNm1GaTN1eDd0VU5vemwrY09pK1Z2aW9vdlowZmhCNFR6bVg2
    ZmJKWlFaa2pTTkhDNnFyU050ZytHM1BsWFBJCnhtbWRmUEZRTDk5MWhuc213KzhxQ1ByVF
    ZYWWRQQmdPbEZwckNEQVhvM0RIU0hMS1YrZmNQcmdDNzNxMkpwdXMKZVNTdlBGenJwQitj
    RVVDdVpNc2VlN2VyVHExNlpZSFlxa0NMRHRVQ2dZRUF5ZTlLdWU1NGl2UE4xZEM1TzlhTA
    psSEgvT2NNcGRVYWs1SHVweFZtT05VUnFUTVFEQ08ydytlWmRPRUs1YkxTVGZZbFI4d0do
    ODMzRWFpZklZcCtICnNPM2hJdFIvWDhTa1FGR1YraHNBTzdBY3BwdG4zd214emY1SVFzR2
    g1aHoremVlYXdHclRVbG92eGtvcHNub2MKOG1HNjVHN2FSYmFNUVVsNjZTT1B3cDg9Ci0t
    LS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
kind: Secret
metadata:
  name: kubebuilder-webhook-server-cert-58c69t76c2
  namespace: kubebuilder-system
type: kubernetes.io/tls
